server:
  port: 9009

spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 192.168.217.129

aliyun:
  sms:
    accessKeyId:
    accessKeySecret:
    template_code: SMS_
    sign_name: 模板
